version: "3"
services:
  olaf:
    build:
      context: .
    volumes:
      - .:/opt/olaf
    ports:
      - "5000:5000"
    depends_on:
      - mongo1
      - mongo2
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:latest
    expose:
    - 27017
    ports:
      - 27011:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:latest
    expose:
    - 27017
    ports:
    - 27012:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
