version: "3"
services:
  olaf:
    build:
      context: .
    ports:
      - "127.0.0.1:${EXTERNAL_PORT}:5000"
    env_file:
      - olaf.env
    environment:
      - APP_URL=0.0.0.0
      - APP_PORT=5000
      - APP_RELOAD=False
      - APP_DEBUG=False
      - EXTRA_ADDONS=/opt/addons
      - MONGODB_HOST=mongodb1
      - MONGODB_REPLICASET_ID=rs0
      - MONGODB_REPLICASET_ENABLE=TRUE
      - MONGODB_TIMEOUT=30000
    depends_on:
      - mongodb1
      - mongodb2
    volumes:
      - ./addons:/opt/addons
  mongodb1:
    image: mongo:4.4
    restart: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--logpath", "/var/log/mongodb/mongo.log" ]
  mongodb2:
    image: mongo:4.4
    restart: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--logpath", "/var/log/mongodb/mongo.log" ]
