version: "3"
services:
  olaf:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - olaf.env
    environment:
      - APP_URL=0.0.0.0
      - APP_PORT=5000
      - APP_RELOAD=False
      - APP_DEBUG=False
      - MONGODB_HOST=mongodb1
      - MONGODB_REPLICASET_ID=rs0
      - MONGODB_REPLICASET_ENABLE=TRUE
      - MONGODB_TIMEOUT=30000
    depends_on:
      - mongodb1
      - mongodb2
  mongodb1:
    image: mongo:latest
    restart: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongodb2:
    image: mongo:latest
    restart: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]